courses/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_detail, name='text'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail, name='quiz'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create, name='create_quiz'),
    url(r'(?P<course_pk>\d+)/create_text/$', views.text_create, name='create_text'),
    url(r'(?P<course_pk>\d+)/edit_quiz(?P<quiz_pk>\d+)/$', views.quiz_edit, name='edit_quiz'),
    url(r'(?P<course_pk>\d+)/edit_text(?P<text_pk>\d+)/$', views.text_edit, name='edit_text'),
    url(r'(?P<quiz_pk>\d+)/edit_question(?P<question_pk>\d+)/$', views.edit_question, name='edit_question'),
    url(r'(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$', views.create_question, name='create_question'),
    url(r'(?P<question_pk>\d+)/create_answer/$', views.answer_form, name='create_answer'),
    url(r'by/(?P<teacher>[-\w]+)/$', views.courses_by_teacher, name='by_teacher'),
    url(r'search/$', views.search, name='search'),
    url(r'admin_view/(?P<pk>\d+)/$', views.course_detail_admin, name='detail_admin_view'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^admin/', admin.site.urls),
    url(r'^suggest/$', views.suggestion_view, name='suggestion'),
    url(r'^$', views.hello_world, name='home'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

urlpatterns += staticfiles_urlpatterns()

handler404 = 'views.my_404_view'

courses/models.py
from django.core.urlresolvers import reverse
from itertools import chain
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import truncatechars

STATUS_CHOICES = (
    ('i', 'In Progress'),
    ('r', 'In Preview'),
    ('p', 'Published'),
)


# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    teacher = models.ForeignKey(User)
    subject = models.CharField(default='', max_length=100)
    published = models.BooleanField(default=False)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='i')

    def __str__(self):
        return self.title

    def time_to_complete(self):
        from courses.templatetags.course_extras import time_estimate
        return "{} min.".format(time_estimate(len(self.description.split())))

    def total_steps(self):
        return Text.objects.filter(course=self).count()+Quiz.objects.filter(course=self).count()


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    published = models.BooleanField(default=False)
    # content = models.TextField(blank=True, default='')

    class Meta:
        abstract = True
        ordering = ['order', ]

    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')
    step_type = 'Text'

    def get_absolute_url(self):
        return reverse('courses:text', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id
        })


class Quiz(Step):
    total_questions = models.IntegerField(default=4)
    step_type = 'Quiz'
    times_taken = models.IntegerField(default=0, editable=False)

    class Meta:
        verbose_name_plural = "Quizzes"

    def get_absolute_url(self):
        return reverse('courses:quiz', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id
        })


class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    order = models.IntegerField(default=0)
    prompt = models.TextField()
    published = models.BooleanField(default=False)

    class Meta:
        ordering = ['order', ]

    def get_absolute_url(self):
            return self.quiz.get_absolute_url()

    def __str__(self):
            return self.prompt


class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)
    published = models.BooleanField(default=False)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.text

    @property
    def short_question(self):
        return truncatechars(self.question, 50)

courses/forms.py
from django import forms

from . import models


class TextForm(forms.ModelForm):
    class Meta:
        model = models.Text
        fields = [
            'title',
            'description',
            'order',
            'content',
            'published',
        ]


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',
            'order',
            'total_questions',
            'published',
        ]
        # exclude = [
        #     'course',
        # ]


class TrueFalseQuestionForms(forms.ModelForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = [
            'order',
            'prompt'
        ]


class MultipleChoiceQuestionForm(forms.ModelForm):
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = [
            'order',
            'prompt',
            'shuffle_answers'
        ]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'order',
            'text',
            'correct'
        ]


AnswerFormSet = forms.modelformset_factory(
    models.Answer,
    form=AnswerForm,
    extra=2,
)


AnswerInlineFormSet = forms.inlineformset_factory(
    models.Question,
    models.Answer,
    extra=2,
    fields=('order', 'text', 'correct'),
    formset=AnswerFormSet,
    min_num=1,
)

courses/views.py
from itertools import chain
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.db.models import Q, F, Count, Sum, When, Case, IntegerField

from . import forms
from . import models


def course_list(request):
    courses = models.Course.objects.filter(
        published=True
    ).annotate(
        total_steps=Count(
            Case(When(text__published=True, then=F('text__id')),
                 output_field=IntegerField(),
                 ), distinct=True
        ) + Count(
            Case(When(quiz__published=True, then=F('quiz__id')),
                 output_field=IntegerField(),
                 ), distinct=True
        )
    )
    total = courses.aggregate(total=Sum('total_steps'))
    return render(request, 'courses/course_list.html', {
        'courses': courses,
        'total': total
    })


def course_detail(request, pk):
    try:
        course = models.Course.objects.prefetch_related(
            'quiz_set', 'text_set', 'quiz_set__question_set'
        ).get(pk=pk, published=True)
    except models.Course.DoesNotExist:
        raise Http404
    else:
        steps = sorted(chain(
            course.text_set.filter(published=True),
            course.quiz_set.filter(published=True)
        ), key=lambda step: step.order)
    # -------Old queries-----
    # course = get_object_or_404(models.Course, pk=pk, published=True)
    # steps = sorted(chain(course.text_set.filter(published=True),
    #                      course.quiz_set.filter(published=True)
    #                      ),
    #                key=lambda step: step.order)
    view_mode = 'userview'
    return render(request, 'courses/course_detail.html', {
        'course': course,
        'steps': steps,
        'viewmode': view_mode,

    })


@login_required
def course_detail_admin(request, pk):
    course = get_object_or_404(models.Course, pk=pk)
    steps = sorted(chain(course.text_set.all(), course.quiz_set.all()),
                   key=lambda step: step.order)
    view_mode = 'adminview'
    return render(request, 'courses/course_detail.html', {
        'course': course,
        'steps': steps,
        'viewmode': view_mode,
    })


def text_detail(request, course_pk, step_pk):
    text = get_object_or_404(models.Text,
                             course_id=course_pk,
                             pk=step_pk,
                             course__published=True)
    return render(request, 'courses/text_detail.html', {'step': text})


def quiz_detail(request, course_pk, step_pk):
    try:
        step = models.Quiz.objects.select_related(
            'course'
        ).prefetch_related(
            'question_set',
            'question_set__answer_set',
        ).get(
            course_id=course_pk,
            pk=step_pk,
            course__published=True
        )
    except models.Quiz.DoesNotExist:
        raise Http404
    else:
        return render(request, 'courses/quiz_detail.html', {'step': step})
        # quiz = get_object_or_404(models.Quiz,
        #                          course_id=course_pk,
        #                          pk=step_pk,
        #                          course__published=True)


@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course,
                               pk=course_pk,
                               course__published=True)
    form = forms.QuizForm()

    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS, "Quiz Added!")
            return HttpResponseRedirect(quiz.get_absolute_url())

        else:
            messages.add_message(request, messages.ERROR, "Form is not valid!")

    return render(request, 'courses/quiz_form.html', {'form': form,
                                                      'course': course
                                                      })


@login_required
def text_create(request, course_pk):
    course = get_object_or_404(models.Course,
                               pk=course_pk,
                               published=True)
    form = forms.TextForm()

    if request.method == 'POST':
        form = forms.TextForm(request.POST)
        if form.is_valid():
            text = form.save(commit=False)
            text.course = course
            text.save()
            messages.add_message(request, messages.SUCCESS, "Text Added!")
            return HttpResponseRedirect(text.get_absolute_url())

        else:
            messages.add_message(request, messages.ERROR, "Form is not valid!")

    return render(request, 'courses/text_form.html', {'form': form,
                                                      'course': course
                                                      })


@login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz,
                             pk=quiz_pk,
                             course_id=course_pk,
                             course__published=True)
    form = forms.QuizForm(instance=quiz)
    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(form.cleaned_data['title']))
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form,
                                                      'course': quiz.course})


@login_required
def text_edit(request, course_pk, text_pk):
    text = get_object_or_404(models.Text,
                             pk=text_pk,
                             course_id=course_pk,
                             course__published=True)
    form = forms.TextForm(instance=text)
    if request.method == 'POST':
        form = forms.TextForm(instance=text, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(form.cleaned_data['title']))
            return HttpResponseRedirect(text.get_absolute_url())
    return render(request, 'courses/text_form.html', {'form': form,
                                                      'course': text.course})


@login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
    if question_type == 'tf':
        form_class = forms.TrueFalseQuestionForms
    else:
        form_class = forms.MultipleChoiceQuestionForm

    form = form_class()
    answer_forms = forms.AnswerInlineFormSet(
        queryset=models.Answer.objects.none()
    )

    if request.method == 'POST':
        form = form_class(request.POST)
        answer_forms = forms.AnswerInlineFormSet(
            request.POST, queryset=models.Answer.objects.none()
        )
        if form.is_valid() and answer_forms.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, 'Added question')
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/question_form.html', {'quiz': quiz,
                                                          'form': form,
                                                          'formset': answer_forms})


@login_required
def edit_question(request, quiz_pk, question_pk):
    question = get_object_or_404(models.Question,
                                 pk=question_pk, quiz_id=quiz_pk)
    if hasattr(question, 'truefalsequestion'):
        form_class = forms.TrueFalseQuestionForms
        question = question.truefalsequestion
    else:
        form_class = forms.MultipleChoiceQuestionForm
        question = question.multiplechoicequestion
    form = form_class(instance=question)
    answer_forms = forms.AnswerInlineFormSet(
        queryset=form.instance.answer_set.all()
    )

    if request.method == 'POST':
        form = form_class(request.POST, instance=question)
        answer_forms = forms.AnswerInlineFormSet(
            request.POST,
            queryset=form.instance.answer_set.all()
        )
        if form.is_valid() and answer_forms.is_valid():
            form.save()
            answers = answer_forms.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            for answer in answer_forms.deleted_objects:
                answer.delete()
            messages.success(request, 'Updates question')
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/question_form.html', {'form': form,
                                                          'quiz': question.quiz,
                                                          'formset': answer_forms})


@login_required
def answer_form(request, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk)

    formset = forms.AnswerFormSet(queryset=question.answer_set.all())

    if request.method == "POST":
        formset = forms.AnswerFormSet(request.POST,
                                      queryset=question.answer_set.all())
        if formset.is_valid():
            answers = formset.save(commit=False)
            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, "Added answers!")
            return HttpResponseRedirect(question.quiz.get_absolute_url())

courses/templates/courses/answer_form.html
{% extends 'courses/layout.html' %}
{% load course_extras %}

{% block title %}
    {{ question|default:"New Answer" }} |
    {{ question.quiz.course.title }} {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <li>
        <a href="{% url 'courses:detail' pk=question.quiz.course.pk %}">
            {{ question.quiz.course.title }}
        </a>
    </li>
    <li>
        <a href="{% url 'courses:quiz' course_pk=question.quiz.course.pk step_pk=question.quiz.pk %}">
            {{ question.quiz.title }}
        </a>
    </li>
    <li>
    {{ question.prompt }}
    </li>
{% endblock %}


{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>

    <div class="row columns"></div>
        <h1>Answers:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <section>
                {{ formset }}
            </section>
            <input type="submit" class="button" value="Save!">
        </form>
    </div>
{% endblock %}

courses/templates/courses/course_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
        <article>
            <h1 class="">{{ course.title }}
            {% if user.is_authenticated %}
                <b>[{{ viewmode }}]</b>
            {% endif %}
            </h1>
            Course written by <a href="{% url "courses:by_teacher" teacher=course.teacher.username %}">{{ course.teacher.first_name }} {{ course.teacher.last_name }}</a>

            <div class="callout secondary">
                {{ course.description|markdown_to_html }}
            </div>

            <dl >
                {% for step in steps %}
                    <div  {% if user.is_authenticated and step.published == False %}style="background-color: #ffe0d7" {% endif %}>
                        <dt>
                            {{ step.step_type }}: <a href="{{ step.get_absolute_url }}">
                                {{ step.title }}
                            </a>
                        </dt>
                        <dd>{{ step.description|markdown_to_html }}</dd>
                        {% if step.step_type == 'Text' %}
                            <small><i>Estimated time: {{ step.content|wordcount|time_estimate }}
                            minute{{ step.content|wordcount|time_estimate|pluralize }}
                            </i></small>
                        {% endif %}
                        {% if not forloop.last %}
                            <hr/>
                        {% endif %}
                    </div>
                    {% if step.question_set.all %}
                        Total questions {{ step.question_set.count }}
                    {% endif %}
                {% endfor %}
            </dl>
        </article>

        {% if user.is_authenticated %}
            <hr>
            <a href="{% url 'courses:create_text' course_pk=course.id %}" class="button">
                New Text
            </a>

            <a href="{% url 'courses:create_quiz' course_pk=course.id %}" class="button">
                New Quiz
            </a>
        {% endif %}
        {% if user.is_authenticated and viewmode == 'userview' %}
            <hr>
            <b>Unpublished</b> Steps are hidden<br>
            <a href="{% url 'courses:detail_admin_view' pk=course.id %}">View Published and Unpublished Steps</a>
        {% elif user.is_authenticated and viewmode == 'adminview' %}
            <hr>
            All <b>Published and Unpublished</b> steps are listed<br>
            <a href="{% url 'courses:detail' pk=course.id %}">View only Published Steps</a>
        {% endif %}
    </div>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}All{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <p>Total number of quizes and steps: {{ total.total }}</p>
    <div class="row">
        {%  for course in courses %}
            <div class="small-6 columns">
                <div class="callout">
                    <h5><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></h5>
                    by <i><a href="{% url "courses:by_teacher" teacher=course.teacher.username %}">{{ course.teacher.first_name }} {{ course.teacher.last_name }}</a></i>
                    <div class="card-copy">
                        {{ course.description|markdown_to_html|striptags|truncatewords:8 }}
                        {% if course.total_steps %}
                            <p><strong>
                                Steps: {{ course.total_steps }}
                            </strong></p>
                        {% endif %}
                    </div>
                </div>
            </div>

            {% if forloop.counter|divisibleby:"2" %}
                </div>
                <div class="row">
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

courses/templates/courses/course_nav.html
{% for course in courses %} 
    <li><a href="{% url 'courses:detail' pk=course.id %}">
        {{ course.title }}
    </a></li>
{% endfor %}

courses/templates/courses/layout.html
{% extends "layout.html" %}

{% block title %}Courses | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <ul class="breadcrumbs">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'courses:list' %}">Courses</a></li>
        {% block breadcrumbs %}{% endblock %}
    </ul>
{% endblock %}

courses/templates/courses/question_form.html
{% extends 'courses/layout.html' %}
{% load course_extras %}

{% block title %}
    {{ form.instance.prompt|default:"New question" }} |
    {{ quiz.course.title }} {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <li>
        <a href="{% url 'courses:detail' pk=quiz.course.pk %}">
            {{ quiz.course.title }}
        </a>
    </li>
    <li>
        <a href="{% url 'courses:quiz' course_pk=quiz.course.pk step_pk=quiz.pk %}">
            {{ quiz.title }}
        </a>
    </li>
{% endblock %}


{% block content %}
    <div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.prompt|default:"Make a new question" }}</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            {{ formset.management_form }}
            <table role="grid" class="stack hover" style="width: 100%">
                <thead>
                    <tr>
                        <th scope="col" class="text-center" style="width: 10%">Order</th>
                        <th scope="col" class="text-center">Text</th>
                        <th scope="col" class="text-center" style="width: 10%">Correct?</th>
                        <th scope="col" class="text-center" style="width: 10%">Delete?</th>
                    </tr>
                </thead>
                <tbody class="order">
                    {% for form in formset %}
                        <tr class="answer-form" {% if form.instance.pk %}item{% else %}new{% endif %}>
                            <td>{{ form.id }}{{ form.order }}</td>
                            <td>{{ form.text }}</td>
                            <td class="text-center">{{ form.correct }}</td>
                            {% if form.instance.pk %}
                                <td class="text-center">{{ form.DELETE }}</td>
                            {% else %}
                                <td class="text-center"></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <input type="submit" class="button" value="Save!">
        </form>

{#      We don't need to show all answers anymore, as we have a formset#}
{#        {% if user.is_authenticated and form.instance.pk %}#}
{#            <hr>#}
{#            {% for answer in form.instance.answer_set.all %}#}
{#                <div class="callout">{{ answer.text }}</div>#}
{#            {% endfor %}#}
{#            <a href="{% url 'courses:create_answer' question_pk=form.instance.pk %}" class="button">#}
{#                Add answers#}
{#            </a>#}
{#        {% endif %}#}
    </div>
{% endblock %}

courses/templates/courses/quiz_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            <p>{{ step.description }}</p>
            <ol>
                {% for question in step.question_set.all %}
                    <li>
                        <h5>{{ question.prompt }}</h5>
                        {% for answer in question.answer_set.all %}
                            <div class="callout" {% if answer.correct %}style="background-color: #3adb76"{% endif %}>{{ answer.text }}</div>
                        {% endfor %}
                        {% if user.is_authenticated %}
                            <a href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}">Edit question</a>
                        {% endif %}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    </li>
                {% endfor %}
            </ol>
            <br>
        </article>
        {% if user.is_authenticated %}
            <hr>
            <a href="{% url 'courses:edit_quiz' course_pk=step.course.pk quiz_pk=step.pk %}" class="button">
                Edit Quiz
            </a>
            <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='mc' %}" class="button">
                Multiple Choice Question
            </a>
            <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='tf' %}" class="button">
                True/False Question
            </a>
        {% endif %}
    </div>
{% endblock %}

courses/templates/courses/quiz_form.html
{% extends 'courses/layout.html' %}

{% block title %}
    {{ form.instance.title|default:'New Quiz' }}
     | {{ courses.title }} {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.title|default:'Make a new quiz' }}</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
    </div>
{% endblock %}

courses/templates/courses/text_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
    {% if user.is_authenticated %}
        <hr>
        <a href="{% url 'courses:edit_text' course_pk=step.course.pk text_pk=step.pk %}" class="button">
            Edit Text
        </a>
    {% endif %}
{% endblock %}

courses/templates/courses/text_form.html
{% extends 'courses/layout.html' %}

{% block title %}
    {{ form.instance.title|default:'New Text' }}
     | {{ courses.title }} {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.title|default:'Make a new text' }}</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="button" value="Save">
    </form>
    </div>
{% endblock %}