courses/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_detail, name='text'),
    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail, name='quiz'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create, name='create_quiz'),
    url(r'(?P<course_pk>\d+)/create_text/$', views.text_create, name='create_text'),
    url(r'(?P<course_pk>\d+)/edit_quiz(?P<quiz_pk>\d+)/$', views.quiz_edit, name='edit_quiz'),
    url(r'(?P<course_pk>\d+)/edit_text(?P<text_pk>\d+)/$', views.text_edit, name='edit_text'),
    url(r'(?P<quiz_pk>\d+)/edit_question(?P<question_pk>\d+)/$', views.edit_question, name='edit_question'),
    url(r'(?P<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$', views.create_question, name='create_question'),
    url(r'(?P<question_pk>\d+)/create_answer/$', views.answer_form, name='create_answer'),
    url(r'by/(?P<teacher>[-\w]+)/$', views.courses_by_teacher, name='by_teacher'),
    url(r'search/$', views.search, name='search'),
    url(r'admin_view/(?P<pk>\d+)/$', views.course_detail_admin, name='detail_admin_view'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^admin/', admin.site.urls),
    url(r'^suggest/$', views.suggestion_view, name='suggestion'),
    url(r'^$', views.hello_world, name='home'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

urlpatterns += staticfiles_urlpatterns()

handler404 = 'views.my_404_view'

templates/home.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
    <div class="row">
        <h1>Welcome!</h1>
        <P>Our latest course is {% newest_course %}</P>
    </div>
{% endblock %}

templates/layout.html
<!doctype html>
{% load static from staticfiles %}
{% load course_extras %}
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        {% block css %}{% endblock %}
        <script src="{% static 'js/vendor/modernizr.js' %}"></script>
        <meta class="foundation-mq">
    </head>
    <body>
        <nav class="top-bar" role="navigation">
            <section class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu role="menubar">
                    <li class="menu-text">The Learning Site</li>
                    <li class="has-submenu">
                        <a href="#">Courses</a>
                        <ul class="submenu menu vertical" data-submenu role="menu">
                            {% nav_courses_list %}
                            <li><a href="{% url 'courses:list' %}">See all &rarr;</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
            <section class="top-bar-right">
                <form action="{% url 'courses:search' %}" method="GET">
                    <ul class="menu">
                        <li><input type="search" name="q"></li>
                        <li><button type="button" class="secondary small button">Search</button></li>
                    </ul>
                </form>
            </section>
        </nav>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% block content %}{% endblock %}
        <footer class="row columns">
            <hr/>
            <div class="small-6 columns">
                <p>&copy; The Learning Site</p>
            </div>
            <div class="small-6 columns">
                <ul class="inline-list no-bullet float-right">
                    <li><a href="{% url 'courses:list' %}">Courses</a></li>
                </ul>
            </div>
        </footer>
        <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/what-input.min.js' %}"></script>
        <script src="{% static 'js/foundation.min.js' %}"></script>
        {% block javascript %}{% endblock %}
        <script>$(document).foundation();</script>
    </body>
</html>

templates/suggestion_form.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %}Suggest an idea!{% endblock %}

{% block content %}
    <div class="row">
        <form action="" method="POST">
        {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="button">
        </form>
    </div>
{% endblock %}